spring:
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:testdb}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: ${DATABASE_DRIVER:org.h2.Driver}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:create-drop}
    show-sql: true
    database-platform: ${DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
  h2:
    console:
      enabled: true
  web:
    cors:
      allowed-origins: "http://localhost:5173"
      allowed-methods: "GET,POST,PUT,DELETE"
      allowed-headers: "*"
      allow-credentials: true


app:
  client-origin: ${CLIENT_ORIGIN:http://localhost:5173}

azure:
  storage:
    account-name: ${AZURE_STORAGE_ACCOUNT_NAME:default-account}
    account-key: ${AZURE_STORAGE_ACCOUNT_KEY:default-key}
    container-name: ${AZURE_STORAGE_CONTAINER_NAME:images}
